### ISSUE TITLE
Not able to find android.js and android-hybrid.js

### ISSUE THREAD

**Issue by saravadeo** [hamsterksu/appium-xwalk#2]
Hi @hamsterksu 

I writing Appium test for Web app, and I am getting same session not found exception. After lot of search I found your solution.But I am not able to find android.js and android-hybrid.js. 

Can you plz help me out?

**Comment by hamsterksu** [comment]
@saravadeo 
maybe appium has changed something inside. i don't track this project anymore. 

in my case it located in 
`node_modules/appium/lib/devices/android/android.js` and `node_modules/appium/lib/devices/android/android-hybrid.js`
